### ISSUE TITLE
Synchronization field return error of range

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi#3]
Hi, @DIOHz0r and @btry 

Could we discuss here this issue to see if you can if it and make a PR in the GLPI Core?

https://dev.flyve.org/glpi/apirest/search/User/?forcedisplay[20]=28&range=0-1

```JSON
[
    "ERROR_RANGE_EXCEED_TOTAL",
    "Provided range exceed total count of data: ; view documentation in your browser at https://dev.flyve.org/glpi/apirest.php/#ERROR_RANGE_EXCEED_TOTAL"
]
```

```JSON
"28": {
    "name": "Synchronization field",
    "table": "glpi_users",
    "field": "sync_field",
    "datatype": "string",
    "nosearch": false,
    "nodisplay": false,
    "available_searchtypes": [
        "contains"
    ],
    "uid": "User.sync_field"
},
```

**Comment by btry** [comment]
As far as I see, the request returns no result, then the range 0-1 specifies more results  than those actually found.

**Comment by ajsb85** [comment]
@btry The request return an error

**Comment by ajsb85** [comment]
@btry Return no result is the response expected

**Comment by btry** [comment]
> @btry Return no result is the response expected

I disagree: other products already use this API, and if it was designed this way for some reason. So it belongs to Flyve MDM to follow the specification. This behavior was created before Flyve MDM consumes it. Changing it only to satisfy needs of Flyve MDM may introduce BC to other applications consuming the API.

That said, I agree to the fact that returning an empty set is more graceful. I wound not consider this being a bug. However I found that no result is returned when we set a forcedisplay as you described. This needs investigation.

**Comment by ajsb85** [comment]
@btry "User.sync_field"  need to be null as default.

**Comment by ajsb85** [comment]
https://dev.flyve.org/glpi/apirest/search/User/?forcedisplay[0]=30&range=0-1

Example response for null in the User.AuthLDAP.name

```JSON
{
    "totalcount": 78,
    "count": 2,
    "sort": 1,
    "order": "ASC",
    "data": [
        {
            "1": "0123456789ABCDEF",
            "30": null,
            "80": "Root entity > rafaelje@gmail.com"
        },
        {
            "1": 1162186473,
            "30": null,
            "80": "Root entity > rafaelje@gmail.com"
        }
    ],
    "content-range": "0-1/78"
}
```

```
    "30": {
        "name": "LDAP directory for authentication",
        "table": "glpi_authldaps",
        "field": "name",
        "datatype": "dropdown",
        "nosearch": false,
        "nodisplay": false,
        "available_searchtypes": [
            "contains",
            "equals",
            "notequals"
        ],
        "uid": "User.AuthLDAP.name"
    },
```

**Comment by ajsb85** [comment]
It's a valid range? "0--1/"

```JSON
{
    "totalcount": null,
    "count": 0,
    "sort": 1,
    "order": "ASC",
    "content-range": "0--1/"
}
```

**Comment by btry** [comment]
try the following : 
https://dev.flyve.org/glpi/apirest/search/User/?forcedisplay[20]=28&range=0-1
 the request wil lreturn a range error

next try
https://dev.flyve.org/glpi/apirest/search/User/?forcedisplay[20]=28
observe there are no result. Then the range error is theexpected behavior

now try 
{{base_url}}/search/User/
observe there are some results 

The bug is here: why we have no result as long we want to show the sync_field ?
moreover I don't understand why to specify forcedisplay[20]=28 . Having an index value of 20 is useless. You may speciy forcedisplay[]=28 for the same result.

**Comment by ajsb85** [comment]
Is it a valid range? "0--1/"

Yes, this one is the result:

```JSON
{
    "totalcount": null,
    "count": 0,
    "sort": 1,
    "order": "ASC",
    "content-range": "0--1/"
}
```

Is totalcount null valid? 
Why count use 0 instead null and totalcount null instead 0?
Is the range "0--1/" valid?

And yes, does not matter the index of the forcedisplay.

**Comment by btry** [comment]
The result if not relevant. There was an upgrade issue on the dev server. Solving this upgrade issue solved the behavior of this request.

**Comment by ajsb85** [comment]
Bug free!
Handle it (the upgrade issue) in the future.
